[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
bw-recorder = "Pwr6Zo12iYxEqqeaLsWXcaCuw5bw5M3QdZxFnULhjmU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn anchor-tests"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false
